### ISSUE TITLE
Entering a node named 'constructor' causes error and no graph rendered

### ISSUE THREAD

**Issue by magjac** [magjac/graphviz-visual-editor#265]
E.g. this DOT source:
```
digraph {
    constructor
}
```
causes this error in the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at dot.js:87:40
    at Array.forEach (<anonymous>)
    at e.value (dot.js:69:14)
    at dot.js:71:14
    at Array.forEach (<anonymous>)
    at e.value (dot.js:69:14)
    at e.value (dot.js:64:10)
    at e.value (dot.js:15:10)
    at new e (dot.js:11:10)
    at t.value (Graph.js:139:29)
``` 
Live example: http://magjac.com/graphviz-visual-editor/?dot=digraph%20%7B%0A%20%20%20%20constructor%0A%7D

**Comment by magjac** [comment]
The root cause of this is that information about all nodes are stored in an internal JavaScript object and that 'constructor' is a property of the JavaScript Object type, from which all JavaScript objects inherit. Therefore a check that checks if a node has already been stored in this object fails, because the inherited property already exists, but without the correct information.
